---
- name: Install Nagios
  tags: ubuntu
  apt:
    name: nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Ensure Nagios is started and enabled (Ubuntu)
  service:
    name: nagios4
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Enable EPEL repo (CentOS)
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: Install Nagios core and essential (CentOS)
  yum:
    name:
      - nagios
      - nagios-plugins
      - nagios-plugins-disk
      - nagios-plugins-http
      - nagios-plugins-load
      - nagios-plugins-ping
      - nagios-plugins-procs
      - nagios-plugins-users
    state: present
  when: ansible_distribution == "CentOS"

- name: Ensure Nagios service is started and enabled (CentOS)
  service:
    name: nagios
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"
