---
 - name: Install apache and php for Ubuntu Servers
   apt:
     name: 
       - apache2
       - libapache2-mod-php
     state: latest
   when: ansible_distribution == "Ubuntu"

 - name: Install apache and php for CentOS servers
   dnf:
     name: 
       - httpd
       - php
     state: latest
   when: ansible_distribution == "CentOS"

